%\VignetteIndexEntry{RECONR data intro}
%\VignetteDepends{rsbml,BiGGR}
%\VignettePackage{RECONR}
%
% NOTE -- ONLY EDIT THE .Rnw FILE!!!  The .tex file is
% likely to be overwritten.
%
\documentclass[12pt]{article}

\usepackage{amsmath,pstricks}
% With MikTeX 2.9, using pstricks also requires using auto-pst-pdf or running
% pdflatex will fail. Note that using auto-pst-pdf requires to set environment
% variable MIKTEX_ENABLEWRITE18=t on Windows, and to set shell_escape = t in
% texmf.cnf for Tex Live on Unix/Linux/Mac.
\usepackage{auto-pst-pdf}
\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}
\usepackage{Sweave}


\textwidth=6.2in
\textheight=8.5in
%\parskip=.3cm
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}


\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rfunarg}[1]{{\texttt{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}

\textwidth=6.2in

\bibliographystyle{plainnat} 
 
\begin{document}
%\setkeys{Gin}{width=0.55\textwidth}

\title{RECONR: A package that provides metabolic reconstruction data to be used within high performance computation framework of R}
\author{Anand K. Gavai}
\maketitle

\section{Introduction}
This document gives an overview on how \Rpackage{RECONR} can be used in a consistent fashion with packages such as 
\Rpackage{BiGGR}. The objects created here allows high performance queries to the reconstruction data as found in BiGG database (\url{http://bigg.ucsd.edu/}) and Reconstruction of Human Genome (\url{http://humanmetabolism.org/}). 
Below are some examples on use of Recon2 data. 


\section{Loading data from SBML objects and listing compartments}
<<>>=
library(RECONR)
data(Recon2)
show(Recon2)
@
\section{Access Reactions}
<<a,eval=FALSE, echo=TRUE>>=
reactions(model(Recon2)) # all reactions
reactions(model(Recon2))$R_YVITEt # individual reaction by name
names(reactions(model(Recon2))) #reaction names
@
\section{Access Species}
<<b,eval=FALSE, echo=TRUE>>=
names(species(model(Recon2)))  #gets the unique names for all the species in the pathway
@
\section{Access Attributes}
<<>>=
attributes(species(model(Recon2))[[1]])$name #gets the name of the species (reactants or substrates or products)
@
\section{Access Kinetic law}
<<>>=
kineticLaw(reactions(model(Recon2))$R_YVITEt)
@
\end{document}
